name: ebook_downloader
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  http: ^0.13.4
  path_provider: ^2.0.7
  vocsy_epub_viewer: ^2.0.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
